[package]
name = "arrsac"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
sample-consensus = { git = "https://github.com/rust-photogrammetry/sample-consensus" }
rand = { version = "0.7.2", default-features = false }
derive_setters = "0.1.2"

[dev-dependencies]
pcg_rand = "0.11.1"
nalgebra = "0.19.0"

[profile.release]
debug = true

